
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes


http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret my_lan_subnet   # My LAN subnet
    - !secret my_docker_bridge    # Also had to add this because something something docker internal network

homeassistant:
  external_url: !secret duckdns_host
  internal_url: !secret internal_url

automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
