
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text-to-speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret my_lan_subnet   # My LAN subnet
    - !secret my_docker_bridge    # Also had to add this because something something docker internal network

  base_url: !secret duckdns_host

google_assistant:
  project_id: home-1dfdd
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true
  expose_by_default: true
  exposed_domains:
    - button
    - camera
    - climate
    - cover
    - event
    - fan
    - group
    - humidifier
    - input_boolean
    - input_button
    - input_select
    - light
    - lock
    - media_player
    - scene
    - script
    - select
    - sensor
    - switch
    - vacuum
    - valve
    - water_heater
